---
 - name: Install Nginx
   become: yes
   apt: name=nginx state=latest

 - name: Start Nginx
   become: yes
   service: name=nginx state=started enabled=true

 - name: Supprimer defaut.conf
   become: yes
   file: path=/etc/nginx/sites-enabled/default state=absent
   notify: nginx reload

 - name: Creation du dossier
   become: yes
   file: path=/home/{{ user }}/{{ domain }} state=directory owner={{ user }}

 - name: Lien vers www
   become: yes
   file: src=/home/{{ user }}/{{ domain }} dest=/var/www/{{ domain }} state=link

 - name: Création de la configuration nginx
   become: yes
   template: src=templates/nginx.j2  dest=/etc/nginx/sites-available/{{ domain }}

 - name: Activation du domain {{ domain }}
   become: yes 
   file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled{{ domain }} state=link
   notify: nginx reload
