---
- name: Ajout de dotDeb aux depot
  apt_repository: repo='{{ item}}'
  with_items:
    - deb http://packages.dotdeb.org jessie all
    - deb-src http://packages.dotdeb.org jessie all

- name: Ajout clef dotdeb
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg

- name: APT update
  apt: update_cache=yes


