---
- name: Installation des serveurs web
  hosts: web
  remote_user: bob
  vars: 
    user: volibear
    domains:
       -  netdeb.local
       -  demo.fr

  roles:
    - utils
    - user
    - nginx


...
