---
 - name: Création d'un utilisateur
   become: yes
   when: user is defined
   user: name={{ user }} comment="Mon user" shell=/usr/bin/zsh
 - name: Ajout de la clef SSH
   become: yes
   when: user is defined
   authorized_key: user={{ user }}  key="{{ lookup('file','~/.ssh/id_rsa.pub')}}"
 - name: "{{ user }} devient sudoers"
   become: yes
   when: user is defined
   template: src=templates/sudoers.j2 dest=/etc/sudoers.d/{{ user }}-sudoer validate='visudo -cf %s'

